name: run
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install deps
              run: npm install
            - name: run
              run: npm run start
    test:
        needs: [lint]
        strategy:
          matrix:
            version: [14,16,17]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.version}}
            - name: install deps
              run: npm install
            - name: run
              run: npm run start
    secret:
        runs-on: ubuntu-latest
        steps:
           - name: print-secret
             run: echo ${{ secrets.TEST}}