name: dunewar_react
on: push
jobs:
    lint:
        runs: ubuntu-latest
        steps:
           -name: Checkout
            uses: actions/checkout@v3
           -name: Install deps
            run: npm install
           -name: run
            run: npm run start